### PR TITLE
Add created_by state

### LINKED ISSUE #8: Add created_by state
Model is missing created_by state

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #8

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@johanjanssens Where should I sync this to?

**Comment by johanjanssens** [comment]
@ercanozkaya Needs to be synced into tags component of https://github.com/timble/kodekit-platform master branch.

**Comment by johanjanssens** [comment]
@ercanozkaya Did you complete the sync?

**Comment by ercanozkaya** [comment]
Synced now. See rev: https://github.com/timble/kodekit-platform/commit/f57e1d5327be5dcc112acf7ce3c4a93a3708e7cd

**Comment by johanjanssens** [comment]
Thanks!

**Pull request merged**
