### PR TITLE
Fix deletion of tags without relations

### LINKED ISSUE #6: Fix deletion of tags without relations
When you have a tag with zero relations delete operation does not work.

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #6

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@johanjanssens Can you review? Without this change tags cannot deleted unless they are connected to at least one row

**Comment by johanjanssens** [comment]
@ercanozkaya Tags should always be connected to a row, if a tag doesn't have a connection aka becomes orphaned it's deleted. A scenario where a tag doesn't have a row shouldn't happen?

**Comment by ercanozkaya** [comment]
@johanjanssens If you go to the tags view in DOCman and add a tag using the new tag form it will be created without having a relation.

**Comment by johanjanssens** [comment]
@ercanozkaya True, didn't consider that one. In that case you are right. I would rewrite the logic slghtly though to show what it does

```
//Delete the relations
if($rowset->count()) {
    $result = $rowset->delete())
}

//Delete the tag
if(!$this->row) {
     $result = parent::delete();
}       
```

**Comment by ercanozkaya** [comment]
Yeah that is cleaner. Rewrote the logic and merged.

**Comment by ercanozkaya** [comment]
And merged into Kodekit as well.

**Comment by johanjanssens** [comment]
Thanks!

**Pull request merged**
